name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        # Este é o passo que não está criando o arquivo
        uses: semgrep/semgrep-action@v1

      # PASSO DE INVESTIGAÇÃO: Vamos listar todos os arquivos para ver o que existe
      - name: List files after scan
        run: ls -R

      - name: Upload SARIF file for GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
