name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # PASSO CORRIGIDO: Agora especificamos qual conjunto de regras usar.
      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: "p/javascript"  # <-- ESTA É A LINHA QUE RESOLVE O PROBLEMA

      - name: Upload SARIF file for GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
