# Nome do Workflow
name: Semgrep Security Scan

# Gatilhos: Roda em push e pull requests para as branches principais
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Permissões necessárias para o workflow funcionar
permissions:
  contents: read # Permite ao workflow ler o código do seu repositório
  security-events: write # Permite ao workflow enviar os resultados para a aba "Security"

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      # PASSO 1: Baixar o código do seu repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # PASSO 2 (O PADEIRO): Executar a análise do Semgrep.
      # Este passo vai ler seu código e criar o arquivo "semgrep.sarif".
      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v2
        with:
          publish_token: ${{ secrets.SEMGREP_APP_TOKEN }} # Opcional, para conectar ao dashboard do Semgrep

      # PASSO 3 (O ENTREGADOR): Fazer o upload do relatório gerado no passo anterior.
      # Este passo só funciona se o Passo 2 for bem-sucedido.
      - name: Upload SARIF file for GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
