name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      # PASSO 1: Baixar o código
      - name: Checkout code
        uses: actions/checkout@v4

      # PASSO 2: Rodar o Semgrep e deixar ele cuidar de tudo
      # Removemos o passo de upload. A própria ação do Semgrep fará isso.
      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v1
