# Nome do Workflow
name: Semgrep Security Scan

# Gatilhos: Roda em push e pull requests para as branches principais
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Permissões necessárias para o workflow funcionar
permissions:
  contents: read      # Permite ao workflow ler o código do seu repositório
  security-events: write # Permite ao workflow enviar os resultados para a aba "Security"

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      # PASSO 1: Baixar o código do seu repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # PASSO 2: Executar a análise do Semgrep
      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v1

      # PASSO NOVO (PARA DEBUG): Listar todos os arquivos para ver o que foi criado
      - name: List files in the directory
        run: ls -R

      # PASSO 3: Fazer o upload do relatório
      - name: Upload SARIF file for GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
